/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Sergio
 */
public class CustomersReportView extends javax.swing.JPanel {

    /**
     * Creates new form CustomersView
     */
    public CustomersReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_customersTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jcb_customers = new javax.swing.JComboBox<>();
        jb_findCustomer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcb_cities = new javax.swing.JComboBox<>();
        jb_findCity = new javax.swing.JButton();
        jb_report = new javax.swing.JButton();
        jb_allCustomers = new javax.swing.JButton();

        setBackground(new java.awt.Color(63, 81, 181));

        jLabel1.setBackground(new java.awt.Color(0, 121, 107));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTE DE CLIENTES");

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jt_customersTable.setBackground(new java.awt.Color(48, 63, 159));
        jt_customersTable.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jt_customersTable.setForeground(new java.awt.Color(255, 255, 255));
        jt_customersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "AP", "AM", "Tel", "@", "RFC", "Cal", "#", "Col", "Cd", "Est"
            }
        ));
        jt_customersTable.setGridColor(new java.awt.Color(63, 81, 181));
        jt_customersTable.setSelectionBackground(new java.awt.Color(63, 81, 181));
        jt_customersTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jt_customersTable);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jcb_customers.setBackground(new java.awt.Color(48, 63, 159));
        jcb_customers.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jcb_customers.setForeground(new java.awt.Color(255, 255, 255));
        jcb_customers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rubi", "Sergio", "Alessandra", "Oswaldo", "Sarah" }));
        jcb_customers.setBorder(null);
        jcb_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_customersActionPerformed(evt);
            }
        });

        jb_findCustomer.setBackground(new java.awt.Color(48, 63, 159));
        jb_findCustomer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jb_findCustomer.setForeground(new java.awt.Color(255, 255, 255));
        jb_findCustomer.setText("Buscar");
        jb_findCustomer.setBorder(null);
        jb_findCustomer.setBorderPainted(false);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ciudad");

        jcb_cities.setBackground(new java.awt.Color(48, 63, 159));
        jcb_cities.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jcb_cities.setForeground(new java.awt.Color(255, 255, 255));
        jcb_cities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tulancingo", "Pachuca" }));
        jcb_cities.setBorder(null);
        jcb_cities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_citiesActionPerformed(evt);
            }
        });

        jb_findCity.setBackground(new java.awt.Color(48, 63, 159));
        jb_findCity.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jb_findCity.setForeground(new java.awt.Color(255, 255, 255));
        jb_findCity.setText("Buscar");
        jb_findCity.setBorder(null);
        jb_findCity.setBorderPainted(false);

        jb_report.setBackground(new java.awt.Color(48, 63, 159));
        jb_report.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jb_report.setForeground(new java.awt.Color(255, 255, 255));
        jb_report.setText("VER REPORTE");
        jb_report.setBorder(null);
        jb_report.setBorderPainted(false);

        jb_allCustomers.setBackground(new java.awt.Color(48, 63, 159));
        jb_allCustomers.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jb_allCustomers.setForeground(new java.awt.Color(255, 255, 255));
        jb_allCustomers.setText("TODOS");
        jb_allCustomers.setBorder(null);
        jb_allCustomers.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_customers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_findCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_cities, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_findCity, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_allCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_findCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_customers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_findCity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_cities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_allCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_report, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_customersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_customersActionPerformed

    private void jcb_citiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_citiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_citiesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jb_allCustomers;
    public javax.swing.JButton jb_findCity;
    public javax.swing.JButton jb_findCustomer;
    public javax.swing.JButton jb_report;
    public javax.swing.JComboBox<String> jcb_cities;
    public javax.swing.JComboBox<String> jcb_customers;
    public javax.swing.JTable jt_customersTable;
    // End of variables declaration//GEN-END:variables
}
