/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Sergio
 */
public class LoginView extends javax.swing.JPanel {

    /**
     * Creates new form CustomersView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_title = new javax.swing.JLabel();
        jl_header1 = new javax.swing.JLabel();
        jtf_user = new javax.swing.JTextField();
        jl_header2 = new javax.swing.JLabel();
        jpf_password = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jl_logo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(63, 81, 181));

        jl_title.setBackground(new java.awt.Color(0, 121, 107));
        jl_title.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jl_title.setForeground(new java.awt.Color(255, 255, 255));
        jl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_title.setText("INICIO DE SESIÓN");

        jl_header1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jl_header1.setForeground(new java.awt.Color(255, 255, 255));
        jl_header1.setText("Usuario");

        jtf_user.setBackground(new java.awt.Color(48, 63, 159));
        jtf_user.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jtf_user.setForeground(new java.awt.Color(255, 255, 255));
        jtf_user.setBorder(null);

        jl_header2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jl_header2.setForeground(new java.awt.Color(255, 255, 255));
        jl_header2.setText("Contraseña");

        jpf_password.setBackground(new java.awt.Color(48, 63, 159));
        jpf_password.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jpf_password.setForeground(new java.awt.Color(255, 255, 255));
        jpf_password.setBorder(null);

        jb_login.setBackground(new java.awt.Color(48, 63, 159));
        jb_login.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jb_login.setForeground(new java.awt.Color(255, 255, 255));
        jb_login.setText("Ingresar al sistema");
        jb_login.setBorder(null);
        jb_login.setBorderPainted(false);

        jl_logo.setFont(new java.awt.Font("Trebuchet MS", 1, 45)); // NOI18N
        jl_logo.setForeground(new java.awt.Color(255, 255, 255));
        jl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_logo.setText("¡Bienvenido(a) a ACME-Store!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl_header1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_user))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl_header2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jpf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 189, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jl_logo)
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(163, 163, 163)
                    .addComponent(jl_title)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_header1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_header2)
                        .addComponent(jpf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(163, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_login;
    public javax.swing.JLabel jl_header1;
    public javax.swing.JLabel jl_header2;
    public javax.swing.JLabel jl_logo;
    public javax.swing.JLabel jl_title;
    public javax.swing.JPasswordField jpf_password;
    public javax.swing.JTextField jtf_user;
    // End of variables declaration//GEN-END:variables
}
