/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Sergio
 */
public class ProductsReportView extends javax.swing.JPanel {

    /**
     * Creates new form CustomersView
     */
    public ProductsReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_productsTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jcb_products = new javax.swing.JComboBox<>();
        jb_findProduct = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcb_desc = new javax.swing.JComboBox<>();
        jb_findDesc = new javax.swing.JButton();
        jb_report = new javax.swing.JButton();
        jb_allProducts = new javax.swing.JButton();

        setBackground(new java.awt.Color(63, 81, 181));

        jLabel1.setBackground(new java.awt.Color(0, 121, 107));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTE DE PRODUCTOS");

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jt_productsTable.setBackground(new java.awt.Color(48, 63, 159));
        jt_productsTable.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jt_productsTable.setForeground(new java.awt.Color(255, 255, 255));
        jt_productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Descripcion", "$ Compra", "$ Venta", "Stock"
            }
        ));
        jt_productsTable.setGridColor(new java.awt.Color(63, 81, 181));
        jt_productsTable.setSelectionBackground(new java.awt.Color(63, 81, 181));
        jt_productsTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jt_productsTable);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Producto");

        jcb_products.setBackground(new java.awt.Color(48, 63, 159));
        jcb_products.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jcb_products.setForeground(new java.awt.Color(255, 255, 255));
        jcb_products.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate", "Cereal", "Galletas", "Pasta", "Atún" }));
        jcb_products.setBorder(null);
        jcb_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_productsActionPerformed(evt);
            }
        });

        jb_findProduct.setBackground(new java.awt.Color(48, 63, 159));
        jb_findProduct.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jb_findProduct.setForeground(new java.awt.Color(255, 255, 255));
        jb_findProduct.setText("Buscar");
        jb_findProduct.setBorder(null);
        jb_findProduct.setBorderPainted(false);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripción");

        jcb_desc.setBackground(new java.awt.Color(48, 63, 159));
        jcb_desc.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jcb_desc.setForeground(new java.awt.Color(255, 255, 255));
        jcb_desc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cacao en polvo para bebidas", "Hojuelas de maíz azucaradas", "Galletas de mesa surtidas", "Pasta de trigo para sopa", "Atún de aleta azul en aceite" }));
        jcb_desc.setBorder(null);
        jcb_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_descActionPerformed(evt);
            }
        });

        jb_findDesc.setBackground(new java.awt.Color(48, 63, 159));
        jb_findDesc.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jb_findDesc.setForeground(new java.awt.Color(255, 255, 255));
        jb_findDesc.setText("Buscar");
        jb_findDesc.setBorder(null);
        jb_findDesc.setBorderPainted(false);

        jb_report.setBackground(new java.awt.Color(48, 63, 159));
        jb_report.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jb_report.setForeground(new java.awt.Color(255, 255, 255));
        jb_report.setText("VER REPORTE");
        jb_report.setBorder(null);
        jb_report.setBorderPainted(false);

        jb_allProducts.setBackground(new java.awt.Color(48, 63, 159));
        jb_allProducts.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jb_allProducts.setForeground(new java.awt.Color(255, 255, 255));
        jb_allProducts.setText("TODOS");
        jb_allProducts.setBorder(null);
        jb_allProducts.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_products, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_findProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_desc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_findDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_allProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_findProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_findDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_allProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_report, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_productsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_productsActionPerformed

    private void jcb_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_descActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jb_allProducts;
    public javax.swing.JButton jb_findDesc;
    public javax.swing.JButton jb_findProduct;
    public javax.swing.JButton jb_report;
    public javax.swing.JComboBox<String> jcb_desc;
    public javax.swing.JComboBox<String> jcb_products;
    public javax.swing.JTable jt_productsTable;
    // End of variables declaration//GEN-END:variables
}
