/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Sergio
 */
public class SalesReportView extends javax.swing.JPanel {

    /**
     * Creates new form CustomersView
     */
    public SalesReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jb_report = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcb_customers = new javax.swing.JComboBox<>();
        jb_findCustomer = new javax.swing.JButton();
        jb_customerSales = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcb_products = new javax.swing.JComboBox<>();
        jb_findProduct = new javax.swing.JButton();
        jb_productSales = new javax.swing.JButton();
        jb_allSales = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_salesTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(63, 81, 181));

        jLabel1.setBackground(new java.awt.Color(0, 121, 107));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTE DE VENTAS");

        jb_report.setBackground(new java.awt.Color(48, 63, 159));
        jb_report.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jb_report.setForeground(new java.awt.Color(255, 255, 255));
        jb_report.setText("VER REPORTE");
        jb_report.setBorder(null);
        jb_report.setBorderPainted(false);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jcb_customers.setBackground(new java.awt.Color(48, 63, 159));
        jcb_customers.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jcb_customers.setForeground(new java.awt.Color(255, 255, 255));
        jcb_customers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rubi", "Sergio", "Alessandra", "Oswaldo", "Sarah" }));
        jcb_customers.setBorder(null);
        jcb_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_customersActionPerformed(evt);
            }
        });

        jb_findCustomer.setBackground(new java.awt.Color(48, 63, 159));
        jb_findCustomer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jb_findCustomer.setForeground(new java.awt.Color(255, 255, 255));
        jb_findCustomer.setText("Buscar");
        jb_findCustomer.setBorder(null);
        jb_findCustomer.setBorderPainted(false);

        jb_customerSales.setBackground(new java.awt.Color(48, 63, 159));
        jb_customerSales.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jb_customerSales.setForeground(new java.awt.Color(255, 255, 255));
        jb_customerSales.setText("CLIENTES");
        jb_customerSales.setBorder(null);
        jb_customerSales.setBorderPainted(false);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto");

        jcb_products.setBackground(new java.awt.Color(48, 63, 159));
        jcb_products.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jcb_products.setForeground(new java.awt.Color(255, 255, 255));
        jcb_products.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate", "Cereal", "Galletas", "Pasta", "Atún" }));
        jcb_products.setBorder(null);
        jcb_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_productsActionPerformed(evt);
            }
        });

        jb_findProduct.setBackground(new java.awt.Color(48, 63, 159));
        jb_findProduct.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jb_findProduct.setForeground(new java.awt.Color(255, 255, 255));
        jb_findProduct.setText("Buscar");
        jb_findProduct.setBorder(null);
        jb_findProduct.setBorderPainted(false);

        jb_productSales.setBackground(new java.awt.Color(48, 63, 159));
        jb_productSales.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jb_productSales.setForeground(new java.awt.Color(255, 255, 255));
        jb_productSales.setText("PRODUCTOS");
        jb_productSales.setBorder(null);
        jb_productSales.setBorderPainted(false);
        jb_productSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_productSalesActionPerformed(evt);
            }
        });

        jb_allSales.setBackground(new java.awt.Color(48, 63, 159));
        jb_allSales.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jb_allSales.setForeground(new java.awt.Color(255, 255, 255));
        jb_allSales.setText("TODAS");
        jb_allSales.setBorder(null);
        jb_allSales.setBorderPainted(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jt_salesTable.setBackground(new java.awt.Color(48, 63, 159));
        jt_salesTable.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jt_salesTable.setForeground(new java.awt.Color(255, 255, 255));
        jt_salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Compras de la tienda"
            }
        ));
        jt_salesTable.setGridColor(new java.awt.Color(63, 81, 181));
        jt_salesTable.setSelectionBackground(new java.awt.Color(48, 63, 159));
        jt_salesTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jt_salesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addComponent(jb_report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_allSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb_products, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_customers, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_findProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_productSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_findCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_customerSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_findCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_customers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_customerSales, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_findProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_productSales, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_allSales, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_report, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_customersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_customersActionPerformed

    private void jcb_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_productsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_productsActionPerformed

    private void jb_productSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_productSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_productSalesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jb_allSales;
    public javax.swing.JButton jb_customerSales;
    public javax.swing.JButton jb_findCustomer;
    public javax.swing.JButton jb_findProduct;
    public javax.swing.JButton jb_productSales;
    public javax.swing.JButton jb_report;
    public javax.swing.JComboBox<String> jcb_customers;
    public javax.swing.JComboBox<String> jcb_products;
    public javax.swing.JTable jt_salesTable;
    // End of variables declaration//GEN-END:variables
}
